<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TTRToMidi</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Shared/FileDialogs.cs" Link="FileDialogs.cs" />
    <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
    <ProjectReference Include="../TTRUtils/TTRUtils.csproj" />
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="plist-cil" Version="2.3.1" />
    <PackageReference Include="Sanford.Multimedia.Midi" Version="6.7.3" />
  </ItemGroup>
</Project>
