<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AvaloniaVersion>12.1.1</AvaloniaVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="MessageBox.Avalonia" Version="12.0.0" />
    <PackageVersion Include="plist-cil" Version="2.3.1" />
    <PackageVersion Include="Sanford.Multimedia.Midi" Version="6.7.3" />
  </ItemGroup>

</Project>
